services:

  db:
    image: postgres:18
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    secrets:
      - db_user
      - db_password
      - db_name
      - secret_key
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt
  secret_key:
    file: ./secrets/secret_key.txt

volumes:
  postgres_data: